------
2012-04-08T16:08:39 WARNING root Developer mode is enabled: this is a security risk and should NOT be enabled on production servers. Developer mode can usually be turned off by setting the `devmode` option to `off` or by removing it from the instance configuration file completely.
------
2012-04-08T16:08:43 INFO ZODB.blob (16378) Blob directory var/blobstorage does not exist. Selected `bushy` layout. 
------
2012-04-08T16:08:43 INFO ZODB.blob (16378) Blob directory '/Users/aclark/Developer/collective/collective.recipe.bluebream/var/blobstorage/' does not exist. Created new directory.
------
2012-04-08T16:08:43 INFO ZODB.blob (16378) Blob temporary directory 'var/blobstorage/tmp' does not exist. Created new directory.
------
2012-04-08T16:08:47 ERROR SiteError http://127.0.0.1:8080/favicon.ico
Traceback (most recent call last):
  File "/Users/aclark/Developer/eggs-directory/zope.publisher-3.13.0-py2.7.egg/zope/publisher/publish.py", line 129, in publish
    obj = request.traverse(obj)
  File "/Users/aclark/Developer/eggs-directory/zope.publisher-3.13.0-py2.7.egg/zope/publisher/browser.py", line 541, in traverse
    ob = super(BrowserRequest, self).traverse(obj)
  File "/Users/aclark/Developer/eggs-directory/zope.publisher-3.13.0-py2.7.egg/zope/publisher/http.py", line 457, in traverse
    ob = super(HTTPRequest, self).traverse(obj)
  File "/Users/aclark/Developer/eggs-directory/zope.publisher-3.13.0-py2.7.egg/zope/publisher/base.py", line 260, in traverse
    obj = publication.traverseName(self, obj, entry_name)
  File "/Users/aclark/Developer/eggs-directory/zope.app.publication-3.14.0-py2.7.egg/zope/app/publication/zopepublication.py", line 198, in traverseName
    ob2 = adapter.publishTraverse(request, nm)
  File "/Users/aclark/Developer/eggs-directory/zope.container-3.12.0-py2.7-macosx-10.7-x86_64.egg/zope/container/traversal.py", line 82, in publishTraverse
    raise NotFound(self.context, name, request)
NotFound: Object: <zope.site.folder.Folder object at 0x111aeb1b8>, name: u'favicon.ico'
------
2012-04-08T16:08:47 ERROR SiteError http://127.0.0.1:8080/favicon.ico
Traceback (most recent call last):
  File "/Users/aclark/Developer/eggs-directory/zope.publisher-3.13.0-py2.7.egg/zope/publisher/publish.py", line 129, in publish
    obj = request.traverse(obj)
  File "/Users/aclark/Developer/eggs-directory/zope.publisher-3.13.0-py2.7.egg/zope/publisher/browser.py", line 541, in traverse
    ob = super(BrowserRequest, self).traverse(obj)
  File "/Users/aclark/Developer/eggs-directory/zope.publisher-3.13.0-py2.7.egg/zope/publisher/http.py", line 457, in traverse
    ob = super(HTTPRequest, self).traverse(obj)
  File "/Users/aclark/Developer/eggs-directory/zope.publisher-3.13.0-py2.7.egg/zope/publisher/base.py", line 260, in traverse
    obj = publication.traverseName(self, obj, entry_name)
  File "/Users/aclark/Developer/eggs-directory/zope.app.publication-3.14.0-py2.7.egg/zope/app/publication/zopepublication.py", line 198, in traverseName
    ob2 = adapter.publishTraverse(request, nm)
  File "/Users/aclark/Developer/eggs-directory/zope.container-3.12.0-py2.7-macosx-10.7-x86_64.egg/zope/container/traversal.py", line 82, in publishTraverse
    raise NotFound(self.context, name, request)
NotFound: Object: <zope.site.folder.Folder object at 0x111aeb1b8>, name: u'favicon.ico'
------
2012-04-08T16:09:06 ERROR SiteError http://127.0.0.1:8080/manage
Traceback (most recent call last):
  File "/Users/aclark/Developer/eggs-directory/zope.publisher-3.13.0-py2.7.egg/zope/publisher/publish.py", line 129, in publish
    obj = request.traverse(obj)
  File "/Users/aclark/Developer/eggs-directory/zope.publisher-3.13.0-py2.7.egg/zope/publisher/browser.py", line 541, in traverse
    ob = super(BrowserRequest, self).traverse(obj)
  File "/Users/aclark/Developer/eggs-directory/zope.publisher-3.13.0-py2.7.egg/zope/publisher/http.py", line 457, in traverse
    ob = super(HTTPRequest, self).traverse(obj)
  File "/Users/aclark/Developer/eggs-directory/zope.publisher-3.13.0-py2.7.egg/zope/publisher/base.py", line 260, in traverse
    obj = publication.traverseName(self, obj, entry_name)
  File "/Users/aclark/Developer/eggs-directory/zope.app.publication-3.14.0-py2.7.egg/zope/app/publication/zopepublication.py", line 198, in traverseName
    ob2 = adapter.publishTraverse(request, nm)
  File "/Users/aclark/Developer/eggs-directory/zope.container-3.12.0-py2.7-macosx-10.7-x86_64.egg/zope/container/traversal.py", line 82, in publishTraverse
    raise NotFound(self.context, name, request)
NotFound: Object: <zope.site.folder.Folder object at 0x111aeb1b8>, name: u'manage'
------
2012-04-08T16:09:51 INFO paste.httpserver.ThreadPool Shutting down threadpool
------
2012-04-08T16:09:51 INFO paste.httpserver.ThreadPool All workers stopped
------
2012-04-08T16:09:51 INFO paste.httpserver.ThreadPool Shutting down threadpool
------
2012-04-08T16:09:51 INFO paste.httpserver.ThreadPool All workers stopped
